baseURL = "/"
languageCode = "en-us"
title = "Bionic Body Fitness"
theme = "alpha-church"

[caches]
[caches.getjson]
maxAge = "10s"

[taxonomies]
tag = "tags"
preacher = "preachers"
series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Trainers"
url = "/trainers"
weight = 2

[[menu.main]]
name = "Services"
url = "#"
weight = 3

# TODO Re-enable these when they exist
[[menu.main]]
 name = "Class Schedule"
 url = "/class_schedule"
 parent = "Services"
 weight = 1

[[menu.main]]
name = "Pricing"
url = "/prices"
parent = "Services"
weight = 2

[[menu.main]]
name = "Register"
url = "/register_new_member"
parent = "Services"
weight = 2

[[menu.main]]
name = "Videos"
url = "https://www.youtube.com/channel/UCLs-1dTfEH0WTU4_Gx4BM4g"
parent = "Services"
weight = 3

[[menu.main]]
name = "Plans"
url = "/plans"
parent = "Services"
weight = 3


[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4

# Paramaters for the whole site
[params]
title = "Bionic Body Fitness"
subtitle = "Joyce Rossiter"
author = "Bill Frasure"

# I wonder what this does...
bible_popups = true
instant_page = true

[params.map]
# For Open Street Map widgets
latitude = "38.847145"
longitude = "-106.947833"
zoom = "12"

[params.contact]
#Use this section to automate contact form.
#Set service to either "netlify" or "formspree"
#For formspree, please setup an account at https://formspree.io/
#For netlify, please read https://www.netlify.com/docs/form-handling/
#
#If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
#If you use formspree, you'll need to set your formspree email address.
service = "netlify"
confirm_page = "/contact_thanks"
# formspree_email=""

#Paramaters for the home/landing page
[params.landing]

[params.landing.banner]
image = "images/PRIVATE_IMAGE_building_and_whetstone.jpg"

[[params.landing.banner.button]]
url = "/contact"
text = "Get in touch"
type = "primary"

[[params.landing.banner.button]]
url = "/class_schedule"
text = "Class Schedule"

#Details for the box below the banner
[params.landing.services]
title = "Your Local Fitness Solution"
text = "Our gym is located in Riverland at [523 Riverland Drive, Crested Butte, CO 81224](https://www.openstreetmap.org/node/6387166010)."
map_location = "Bionic Body Fitness"

[params.landing.feature_icons]
#These feature icons look best if there's an even number of them.
enable = true

#Accent is a colour defined in the CSS file. Choose between 1 and 5
[[params.landing.feature_icons.tile]]
icon = "fa-fist-raised"
icon_pack = "fas"
accent = "1"
title = "Decades of Training Experience"
text = "Personalized Exercises to Match Your Body"
url = "/contact"

[[params.landing.feature_icons.tile]]
icon = "fa-hands-helping"
icon_pack = "fas"
accent = "2"
title = "Group Classes"
text = "[Class Schedule](/class_schedule)"
url = "/class_schedule"

[[params.landing.feature_icons.tile]]
icon = "fa-dumbbell"
icon_pack = "fas"
accent = "5"
title = "Weights"
text = "Targeted, Customized Weight Training"
url = "/prices"

[[params.landing.feature_icons.tile]]
icon = "fa-heartbeat"
icon_pack = "fas"
accent = "3"
title = "Heart Healthy"
text = "High Intensity Classes to get your blood pumping"
url = "/class_schedule"

[params.landing.feature_images]
#These feature images look best if there's an even number of them.
enable = true

[[params.landing.feature_images.tile]]
image = "images/PRIVATE_IMAGE_building_and_whetstone.jpg"
title = "Located in beautiful Riverland"
text = "Convenient for downtown and CB south"
url = "/class_schedule"
button_text = "Class Schedule"

[[params.landing.feature_images.tile]]
image = "images/fembot.jpg"
title = "Exercise Videos"
text = "Supplement your in-house classes with a growing selection of instructional videos"
url = "https://www.youtube.com/channel/UCLs-1dTfEH0WTU4_Gx4BM4g"
button_text="Watch the videos on YouTube"

[params.landing.CTA]
heading = "Get in touch!"
message = "We'd love to hear from you."


# Decide on license here
[params.footer]
copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
"Design: [HTML5 UP](//html5up.net/alpha)",
"[Bionic Body Fitness](//github.com/swoogles/bionicBodyFitness) by [Bill Frasure](//github.com/swoogles)"
]

[[params.links]]
service = "Facebook"
icon = "fa-facebook"
icon_pack = "fab"
link = "//facebook.com/"

# Transform this to Youtube link
[[params.links]]
service = "Podcast"
icon = "fa-podcast"
icon_pack = "fas"
link = "/sermons/index.xml"
